POST  http://127.0.0.1:8000/api/statistics HTTP/1.1
content-type: application/json

{
  "name": "そら",
}

###

POST  http://127.0.0.1:8000/api/todoLists HTTP/1.1
content-type: application/json

{
  "user_id": 1,
  "todo_list": "こんにちは",
  "status": true,
}

###

POST  http://127.0.0.1:8000/api/statistics/day/back HTTP/1.1
content-type: application/json

{
  "data": 2021-04-11
}

###
POST  http://127.0.0.1:8000/api/statistics/week HTTP/1.1
content-type: application/json

